defmodule Demo.Repo.Migrations.AddTicketTsvector do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE tickets
      ADD COLUMN generated_tsvector tsvector
      GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(subject, '') || ' ' || coalesce(body, ''))
      ) STORED;
    """)

    execute("""
    CREATE INDEX tickets_search_idx ON tickets USING GIN(generated_tsvector);
    """)
  end

  def down do
    execute("""
    DROP INDEX tickets_search_idx;
    """)

    alter table(:tickets) do
      remove :generated_tsvector
    end
  end
end
